server:
  port: 8080
  address: 0.0.0.0
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: chat-person
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-person-test
    username: postgres
    password: bodyzxy
  app:
    jwtSecret: ==========================bodyzxy============================
    jwtExpirationMs: 86400000  #24小时
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update  # 使用 update 而不是 create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
  data:
    redis:
      database: 0
      host: 0.0.0.0
      port: 6379
      lettuce:
        pool:
          max-active: 8 #??????
          max-wait: -1 #????????
          max-idle: 8 #??????
          min-idle: 0 #??????
  ai:
    openai:
      api-key: sk-zk2e27818546028c11740ed9f4d71d3f46966c1f2ae9e310
      base-url: https://api.zhizengzeng.com
      chat:
        options:
          temperature: 0.7
    vectors tore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9001}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:adminbodyzxy}
  bucket-name: ${BUCKET_NAME:chat-person-test}
#logging:
#  level:
#    org.springframework: DEBUG
#    org.springframework.test: DEBUG