server:
  port: 8080

spring:
  application:
    name: chat-person
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false
    username: root
    password: bodyzxy
  app:
    jwtSecret: ==========================bodyzxy============================
    jwtExpirationMs: 86400000  #24小时
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: true
  data:
    redis:
      database: 0
      host: 0.0.0.0
      port: 6379
      lettuce:
        pool:
          max-active: 8 #??????
          max-wait: -1 #????????
          max-idle: 8 #??????
          min-idle: 0 #??????
  ai:
    openai:
      api-key: sk-zk2e27818546028c11740ed9f4d71d3f46966c1f2ae9e310
      base-url: https://api.zhizengzeng.com
      chat:
        options:
          temperature: 0.7
    vectors tore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536